---
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
  namespace: netology
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - name: nginx
      port: 80
      nodePort: 30111
    - name: multitool
      port: 8080
      nodePort: 30112
...